### PR TITLE
Update NavigationView, Settings and About according to design

### PR DESCRIPTION
**Pull request by cloudstalker**
Frontend is basically complete for these three parts (except for some animations). Need help with the buttons (feedback, rate) in "About" and general backend stuffs connected to "Settings" (quite confused). For example, I made animation for "Sync now" button but had not implemented the progression tied to synchronization. Also the Passwordbox's header color is still black albeit setting them to white.

Can we have a "Alpha" branch in the repository since without the right "Settings" backend implementations the app is not working?

Added MS community toolkit.

### CODE REVIEW

**Comment by NPadrutt** [comment]
Thanks for your pull request! I had a look and I think it looks quite nice (I love the animation after the backup is complete :) )

To link up the functions you have to assign the correct view models to the datacontext of the  user controls.
Not sure if we need a alpha branch. We can work on the feature on your PR Branch until it's finished. But maybe might be a develop branch for integration be an idea.

**Comment by cloudstalker** [comment]
Yeah I am in love with dealing with animations after this, previously never animating anything in uwp. They are so cool. So let me list the things to be done:
- passwordbox style
- passwordboxes appear/disappear animation
- smoother transition when changing window height
- settings connecting to viewmodel
- about buttons (feedback, rate us) click event
- other bugs should there be any

**Comment by NPadrutt** [comment]
I won't be able to help you with the design, but hit me up if you need furhter advice with hooking up the functionality.
also I would recomend that you merge the master sometime. there seems to be some conflicts.

**Comment by NPadrutt** [comment]
mh, it's the MoneyFox.Business.Tests project file. that's strange indeed.

**Comment by cloudstalker** [comment]
Most settings commands should be find since I keep their {Binding xxCommand}. However for theme one since now I use toggleswitch I cannot use previous combo box binding. When I press F12 to trace the command VS cannot find the source so I need some help with this one. Also I cannot find the backup button command from the backupview.xaml for the "Sync Now" button.
Wow, just a `xmlns:viewModels="using:MoneyFox.Business.ViewModels" ` resolved every conflicts, after I tried to merge upstream/master into my UI branch but discard all the changes (done in GitHub Desktop). What did I do lol?

**Comment by NPadrutt** [comment]
Do you think the toggle switch is the better choice? Isn't it more something like to activate or deactivate something instead of choose between two options? Maybe a radio box group (if something like that is available ^^)

for the merge, I think you just didn't resolve it or reverted all changes from the main branch :P for example is the README the old one again and the git ignore has some merge markers in it :D I can try to resolve it if you want?

**Comment by cloudstalker** [comment]
Toggleswitch for Dark Mode on/off is not a bad choice at least IMO. Or maybe "night mode" is the way to go? Radio box group is also not hard to implement fyi.
Please go ahead. I am very confused about this conflict or merge situation. Say, how is it that I discard all the merges from upstream/master and pass this conflict check? And now when I try to merge it again it says nothing to change.

**Comment by NPadrutt** [comment]
Ah right. That makes sense :)

The thing with git merges is, that they insert something like this to your files where it can't merge:
```
<<<<<<< HEAD
*.userprefs
=======
MoneyFox.Droid.nuget.targets
>>>>>>> MoneyFox/master
```

That means you can just commit that and have it "resolved" then (so you just have the markers in your code then). 
What happened when you discarded the changes is a bit strange though ^^

**Comment by cloudstalker** [comment]
OK appreciate the help :)

**Comment by NPadrutt** [comment]
I think it somehow the merge went down the right way :D the only thing I see is that you reverted a renaming of a user control I made. but that shouldn't do any harm. 
The only thing is the one in the gitignore I noted before. Just remove the merge indicators (<<<<, >>>>, ==== ) and we should be fine :)

**Comment by NPadrutt** [comment]
sorry, missclicked^^

**Comment by NPadrutt** [comment]
I think I was able to resolve the issues. I made a new branch based on the master and merged your changes over with cherry pick (I hope I didn't miss one). this is the new branch : https://github.com/NPadrutt/MoneyFox.Windows/tree/UI-new

you should now merge this into your branch. 
(not entirely sure, but I guess this command should do that when you are on your branch:
`git pull https://github.com/NPadrutt/MoneyFox.Windows.git UI-new`
)

there will be two conflicts. Resolve them using my change instead of yours. as far as I could see this worked out. Afterwards the things I checked looked good.

**Comment by cloudstalker** [comment]
Oh crap, after merging when I compile the project it errs of something like "Name cannot begin with '<' (HEX 0x3C), line 12, column 1. No file name specified.

**Comment by NPadrutt** [comment]
I noticed some reference issues. A fix is on my branch.
But the message your writing sounds like you haven't finished the merge. As noted above, the < are merge signs git inserts to your code and removes after you deciced which part to keep. Like in the example above:

```
<<<<<<< HEAD
*.userprefs
=======
MoneyFox.Droid.nuget.targets
>>>>>>> MoneyFox/master
```

you can search for "<<<<<<<" and should find where it is.

**Comment by cloudstalker** [comment]
Yep the <<<< is inside MainView.xaml, inside which was what I did previously after merging and discarding (inserting xmlns:viewModels="using:MoneyFox.Business.ViewModels"). When I merged your UI-new last time there were 3 conflicts, then I just hit commit and now only MainView.xaml gives thie <<<<. There is some pattern here seems like the real thing that's conflicting is MainView.xaml?

**Comment by NPadrutt** [comment]
well, if you have conflicts just hitting commit is soledome a good idea since that means you commit the merge conflict unresolved. ^^
I didn't have them in the mainview, but in a settings user control that I renamed and you changed. but when you can search for the markers you can manually resolve the conflicts and then you should be able to build again.

**Comment by cloudstalker** [comment]
As long as it can build and no conflicts detected we are good eh lol.

**Comment by cloudstalker** [comment]
Hi @NPadrutt can you help me with this settings linking to VM stuff? I copied anything I thought related to this but it is not working (e.g. theme change does not work). You can see the datacontext bindings in SettingsUserControl.xaml and individual controls bindings in their respective xaml's in my latest commit.
Also I just realized one needs to login their OneDrive to be able to sync. So I thought it could be implemented with a login button first and after that a sync button. But when I try to find how you previously did that, the Backup view xaml is empty and I have no idea how it builds up the frontend and the backend with it.

**Comment by NPadrutt** [comment]
I think you have too much of a mix and match between event handler and bindings.  For example:

`<ToggleSwitch Header="Dark Theme" x:Name="ThemeSwitch" AllowFocusOnInteraction="False" IsOn="{Binding ThemeToggled, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}" Toggled="ThemeSwitch_Toggled" Margin="10, 0, 0, 0" Foreground="{StaticResource FlyoverTextColor}">`

In this case I would move everything to a binding and set the content to another binding as well instead of the code behind. That way you can reuse it.

In the case you have code behind for an animation, remove the binding and call the Command in the code behind over the data context. You might have to convert the data context to the bound view model.

The data context binding itself looks fine on a first glance.

Also something to note: ensure you translate the texts with a proper binding for content / texts. See here: https://apply-solutions.atlassian.net/wiki/spaces/MON/pages/413663275/Translations

Regarding the old backup view, I used the same XF page as on the mobile embedded as a user control. https://github.com/MoneyFox/MoneyFox/blob/master/Src/MoneyFox/Views/BackupPage.xaml

**Comment by cloudstalker** [comment]
The toggled event handler fires and the ToggleSwitch.OnContent (or OffContent, depending on IsOn) is set to `+= "(Restart needed)"`. I couldn't see a way (at least a cleaner one) to put this function into binding. Also this function is quite specific here and reusability is a minor concern at least to me. In general I am still quite confused of MVVM about where to put what since it is easy to argue the other way round. Anyway the changing theme function does not work (somehow the app does not remember the setup after restart, which seems to be the case for other switches as well? where does settingsManager of every viewmodel go every launch/exit?).
When everything works I will be sure to add entries to the Strings.resx :)

**Comment by NPadrutt** [comment]
You can make a binding to Toggled and another to the content and then set the value of the ContentProperty when toggled is executed. The advantage of that, besides of having everything in one place (the view model), is that it is testable with a unit test. That's the main reason to put as much as possible to the view model. That of course doesn't apply if you have animation stuff which is plattform dependant. But all the rest should go the view model.

SettingsManager is injected in the SettingsViewModel via the constructor and from there passed down to the sub viewModels:
https://github.com/cloudstalker/MoneyFox/blob/834f77f06e1edeec9a99adccae3eca09746815c4/Src/MoneyFox.Business/ViewModels/SettingsViewModel.cs#L33

Generally speaking that's where it comes to live. To see more about the dependency injection see here and the link in the further information: 
https://apply-solutions.atlassian.net/wiki/spaces/MON/pages/450134017/Dependency+Injection

If the toggle doesn't work, my first step would be to check if the property is bound correctly. AFAIK that property is in the SettingsPersonalizationViewModel. Does the set get called correctly? Also, do you see a warning in the debug output regarding not resolved bindings?

**Comment by NPadrutt** [comment]
Aaah, I have a suspicion what the issue is... 

The Navigation in MvvmCross is not done by navigating to pages but to ViewModels (for all the details and options: https://www.mvvmcross.com/documentation/fundamentals/navigation). So, till now, when we go to the Settings, we call for a navigation to the SettingsViewModel. This loads the SettingsView (based on naming), loads it and applies the SettingsViewModel as DataContext to the page.

The SettingsViewModel now contains all the other user controls and sets the DataContext there. have a look here: https://github.com/cloudstalker/MoneyFox/blob/UI/Src/MoneyFox.Windows/Views/SettingsView.xaml

Now the issue is, that you now have a SettingsUserControl. Since there was never a navigation called to the SettingsViewModel, the "BaseDataContext" is the MainViewModel and not the SettingsViewModel. Therefore the binding to the of the DataContext cannot be resolved since the MainViewModel does not have the properties you bind. Does that make sense?

**Comment by cloudstalker** [comment]
Yeah I get the idea but am confused about some detail. Say how does `navigationService.Navigate<SettingsViewModel>()` get to the respective view as I don't see any reference to the xaml?

**Comment by NPadrutt** [comment]
As stated above, that view is resolved based on the naming. E.g SettingsViewModel searches for SettingsView.xaml.

**Comment by cloudstalker** [comment]
OK but how do I approach this? Manually setting the data context in code I suppose but not sure how to do that.

**Comment by NPadrutt** [comment]
There are several options. Resolve the ISettingsViewModel via the constructor, save it in a property and set the datacontext of the SettingsUserControl and below accordingly.

Or you can move all the properties from the several SettingsViewModels to the MainViewModel and bind from the user Controls directly to them.

I think oth ways do have advantages and disadvantages.

**Comment by cloudstalker** [comment]
OK now it's just "Sync Now" button logic left. My thought is that this button will check up the file in the cloud (if exists) and compare modify date. If local is newer then upload if local is older then download. Is that possible? It would also be great if the function can expose some kind of progress data for the animation purpose.
Also I overlooked the Login/Logout function before when at design phase. Hence, the current UI (regarding synching, login) is not the best imo and I will make a better version later.
All Strings.resw is updated for SettingsUserControl and its children. AboutUserControl will follow shortly.

**Comment by NPadrutt** [comment]
Have a look at the BackuoViewModel and the classes it uses. Some things do already exist. For the progress you can check if the Graph SDK offers something here. But my guess is that it doesn't.  Since the sync is quite fast question is if you could see that much anyway ^^

**Comment by cloudstalker** [comment]
- I have yet to find a way to change the text of the nav view settings item
- VS Blend crashes when loading GeneralView.xaml so I have no idea how to change pivot's appearance at the stage. As a result, the current general view is not great looking but works.

**Comment by cloudstalker** [comment]
Not really. It seems it's something wrong with the solution. It's like all xamls are unable to render the designer.

The error message is some kind of component cache expiration, `NuGet.Configuration, Version=4.7.0.5, Culture=neutral, PublicKeyToken=31bf3856ad364e35`. The message suggests me to restart but that does not work. Whenever I try to open/switch to another xaml or hit the reload designer hyperlink the whole thing crashes.

**Comment by NPadrutt** [comment]
mh, if something with your nuget cache is wrong, try to delete it. then the nuget packages are redownloaded. It is in your user folder under \.nuget the packages folder there.

**Comment by cloudstalker** [comment]
Well it still does not work. Nevermind, I try to copy the xaml code from a clean project.

**Comment by cloudstalker** [comment]
Well now it looks good enough although I still am not able to fully customize the pivot control (due to crash when incorporating custom xaml code, these crashes without any error info are driving me crazy). To wit, I will just ignore my previous plan to cast drop shadow to pivot header and so on, cuz currently the look conforms to the looks of MS's app so why not. Anything else to discuss just let me know :)

**Comment by NPadrutt** [comment]
looks quite nice :) 
two things I noticed:
- Is there a particular reason for the app bar? For me it looks more modern with the content filling out the whole screen
- I wonder if the selected item would be nicer if we use the default indicator on the left. since the two colors have more contrast this could be enough now. and it has a nice moving animation :D what do you think?

**Comment by NPadrutt** [comment]
if we can put the bread crumb navigation there that would be quite nice. 

ah, I see :)

**Comment by NPadrutt** [comment]
this PR seems abandoned and is therefore closed.

**Pull request closed without merging**
