### PR TITLE
Design across platforms

### PR DESCRIPTION
**Pull request by cloudstalker**
Take a look. Right now I have finished the account page design for UWP. The rest should come in a few days. iOS/Android will come after that.  Let me know what you guys think. Thank you.

You can find the new designs under /Designs/UWP

### CODE REVIEW

**Comment by NPadrutt** [comment]
looks nice. Shall I merge this branch or do you want to add more designs / implementation here?

**Comment by cloudstalker** [comment]
Don't need to merge yet. I think I try finish the rest of UWP design first, then we discuss and make changes to it, what function we need what to remove etc (we can refer to your ideas and other issue). After that, we can go ahead and implement the frontend. 
Not sure if we first do UWP frontend then ios/Android frontends, or we agree upon design across all the platforms and implement them at the same time. Which one is more efficient? (still haven't look into Xamarin yet sorry)

**Comment by NPadrutt** [comment]
I would probably create an issue and add the images and discuss it there. In PR's images are not previewed. Then we can add the concrete implementation over a PR.
And I would probably make a split. one for UWP on the desktop and mobile and one for xamarin forms on ios and android.

**Comment by cloudstalker** [comment]
Yeah you are probably right. Not being able to preview images can be annoying. Seems like PR is mainly for text based stuff? However, as I understand issues, perhaps they are not suited for a big change such as revamping whole UI (since there will be tons of images)?
Anyways, not to waste this PR, I think of making a new .md file which show all the images. That way I can organize everything as in issues, also keeping some crucial values such as sizes, colors in place for future reference. What do you think?

**Comment by NPadrutt** [comment]
I would say an issue is like a requirement you can discuss and plan. Ah PR then is the implementation of an requirement. To discuss a design I probably would make something like a design document and attach it in an issue for example as PDF. then everyone can download it and refer to it. If this discussion is a PR of the finished document might make sense so you can refer to that again when you make several issues for the implementation. that way you can break it down in smaller junks of work :)

**Comment by NPadrutt** [comment]
Ah and in such a design guideline you can of course add all the colors and sizes etc. which makes it even more valuable.

**Comment by cloudstalker** [comment]
Using PDF is a good idea! I will be closing this PR. When I finish all the images for UWP I will post an issue. Let's hope GitHub will support previewing images and raw design files (this will be really cool as they contain prototypes showing animations and stuff) some day :/.

**Pull request closed without merging**
