### PR TITLE
issue #1184 

### PR DESCRIPTION
**Pull request by Squawk09**
Is this kinda what you are wanting. I need to add things to IStartAssistant and StartAssistant.  Not sure how the translations work for the string resources.

### CODE REVIEW

**Comment by NPadrutt** [comment]
Hi
Thanks for your contribution! I will review it on Sunday once I'm back home! :)

**Comment by Squawk09** [comment]
No prob, I also accidentally removed the last commit because i had to revert my branch. Didnt realize it did that.  I do now :)

**Comment by NPadrutt** [comment]
What you could have a look at, is why the AppVeyor ibnegration fails. I guess it has some issue with the Android SDK version you have installed (6 instead of 7.0 or 7.1).

**Comment by Squawk09** [comment]
Yes, I do not understand why I am getting this error.  I changed the version in the framework and did NuGet Restore but it still seems to be failing.

**Comment by NPadrutt** [comment]
Have you installed the latest android sdk over the sdk manager?

**Comment by NPadrutt** [comment]
AAH, I guess you still have some old references on the support packages. They changed some things with the newer versions of them.

**Comment by NPadrutt** [comment]
I did some research on the issues. You updates the xamarin.auth nuget. Xamarin.auth has an dependency on certain support packages of google. As it seems now they moved some components from one support package to another. Since you have the new versions with component A) in Package A and the solution references an older version of the support package with component A in Package B, Visual Studio doesn't now which one is the correct to take. This is always a bit nasty on android.. 
I would recommend you, to revert the commit with the nuget update. This should make the project buildable again (local and on the CI).
I will make an sepearte PR with the update Nugets sometimes in the near future.

**Comment by NPadrutt** [comment]
Ah, as an addition. Usually it would be an easy solution to just update all references of the support package to the new one. But since we use the MvvmCross Nuget Packages to reference the support packages and there is no update for them right now, this isn't an option.
We could use other references, but the chance that we have an issue with an dependcy of MvvmCross to an older packages is quite high, so it's easier for the moment to just revert the Nuget update.

**Comment by NPadrutt** [comment]
Alright, besides the issue with the java version when building android, there where an issue in a version of VS 2017 when building UWP apps.
I added some fixes and work arounds. Please merge the master branch. This should fix the CI issues :)

**Comment by NPadrutt** [comment]
ah and regarding the translation: You just have to put translations to the Strings.resx or the english versions on the platform specific projects. I upload them then to crowdin for translation.

Regarding the PR. I think we should have some way to ask if the user wants to get the default categories, for example a dialog or a page in the wizard. what do you think?

**Comment by NPadrutt** [comment]
I'll close this PR. Please reopen when the mentioned points are fixed.

**Pull request closed without merging**
