### PR TITLE
UpdatedTranslations and fix crash

### LINKED ISSUE #1357: Broken Description (Simplified Chinese)
The app supposedly support simplified Chinese but on top of that the app itself is still largely English, the description at Windows Store (Chinese) consists of mostly ????'s (see [screenshot](https://imgur.com/VP0W8lv)).

### LINKED ISSUE #1359: App crash when the recurring switch is on
Platform: Windows 10 1803, x64, UWP.

Steps to reproduce:

1. Open app
2. Create an account
3. Click the "+" at the bottom
4. Turn on the recurring (the one at the end) switch
image
5. Click virtually any button such as save, Accounts, about and get a crash
6. Restart the app you should see the entry is saved. Click it again and go to step 5 and the crash is reproduced. 

Note: Turning off the said switch does not result in a crash.

### LINKED ISSUE #1363: Paymentlist not refreshed when a payment is added or modified
Whenever I add/modify a payment, the list is not refreshed until I revisit the same page.

### PR DESCRIPTION
**Pull request by NPadrutt**
- Fix #1359 
- Update translations partially fixes #1357 
- Updates MvvmCross and Xamarin Forms Packages
- fix #1363

### CODE REVIEW

**Comment by cloudstalker** [comment]
The [crash]( https://github.com/MoneyFox/MoneyFox/issues/1359 ) problem has been resolved.
As for the [translation]( https://github.com/MoneyFox/MoneyFox/issues/1357 ) I saw almost no change. Anything I might help with?

**Comment by NPadrutt** [comment]
Not right now. We'll have a look at this once I added your latest translations

**Comment by NPadrutt** [comment]
@cloudstalker In my tests it looked quite good now. have a look when you have time :)

**Comment by cloudstalker** [comment]
@NPadrutt Yeah most translations and the weekday/month are now in Chinese. Look nice indeed. :)

A few translations are not in place:
"Select statistics"
"Categories"
Which correspond to the title of the respective page of the navigation items (statistics and categories)
"New Category"
When I hit the three dot button at the categories page.

These seem to have come from 

> Resources.resw

.

**Comment by NPadrutt** [comment]
Since this is fixed aswell, I merge this PR.
The translated strings are updated periodically.

**Pull request merged**
