### PR TITLE
Fix amounts with separator chars not parsing bug

### LINKED ISSUE #1116: Issues with Edit Amount if it is converted with seperator sign
if the amount is converted for example as: 3'505.50 it can't be parsed correctly to a double. There changes are not saved correctly.

### PR DESCRIPTION
**Pull request by isLongoria**
Fix #1116 by removing all separator chars from the entered amount.

### CODE REVIEW

**Comment by NPadrutt** [comment]
Hi @isLongoria 
thanks for your PR! :)

would it be possible to make a new Helper to centralize the logic in the AmountString properties so that we don't have it at three different places ?

**Comment by isLongoria** [comment]
Sure thing @NPadrutt , I'll get it done tomorrow. :)

**Comment by isLongoria** [comment]
Updated the logic to a single helper.

**Comment by NPadrutt** [comment]
Great thanks :)

**Pull request merged**
