### PR TITLE
Please add option does not include some accounts in total balance (for example - credit card with negative balance)

### PR DESCRIPTION
**Pull request by jsxw01**
And click on Total balance to see all operations from different accounts for days in one place!

### CODE REVIEW

**Comment by NPadrutt** [comment]
Hi. This seems to be an issue rather than a pull request.
It sounds like you want something as described in issue #321. Is that what you are looking for or do you mean something else?

**Comment by jsxw01** [comment]
Yes, that's right!

**Comment by NPadrutt** [comment]
alright. I guess we can then close this PR for now.
Do you wanna have a look at the issue #321 ?

btw: there is a slack channel for this project. just make drop me a mail with your mailadress if you want an invite.

**Comment by jsxw01** [comment]
Yes, you can close this PR.

Thanks, but I don't use slack)

**Pull request closed without merging**
