### PR TITLE
Added select toggle for passport

### PR DESCRIPTION
**Pull request by Squawk09**
Added selection toggle for passport in security view.

### CODE REVIEW

**Comment by NPadrutt** [comment]
Thanks for your PR! :)
I noticed, that there is no Login prompt at all when I just activate Windows Passport. Is that intended?

**Comment by Squawk09** [comment]
Oh shoot, let me look at it

**Comment by Squawk09** [comment]
@NPadrutt Do you know why this commit included a number of deletions in the Droid.csproj file? Is this something to worry about? 

Thanks!

**Comment by NPadrutt** [comment]
As far as I can see, the changes are only in the droid.csproj.bak file. Since that's just a backup that doesn't really matter. 
In general all the deletions are okey. When we made the change from packges.config to the project.json we could delete all the static references to nuget packages in the csproj. But this change where some months ago. So it's a bit strange to see that they come now ^^

**Comment by NPadrutt** [comment]
thanks! :) 👍

**Pull request merged**
