### PR TITLE
Fixed bugs with updating categories

### PR DESCRIPTION
**Pull request by kg8z**
1. Updated logic to exclude current record when checking for duplicate names.
2. Fixed category update logic that was throwing exceptions upon save.

Issue: #2684 

## PR Type
What kind of change does this PR introduce?

- Bugfix

## What is the current behavior?
When an existing category is edited, clicking the Save button always results in the error "A category with that name already exists." unless the name is changed as part of the edit operation. This is happening because the check for duplicate category names does not exclude the currently opened category from the check. As a result, the ViewModel detects that a category already exists with the same name.

## What is the new behavior?
Saving changes to a Category now correctly checks whether or not the name is in use by another record.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] Tested code on Windows
- [x] Tested code on Android
- [x] Tested code on iOS
- [x] Tests for the changes have been added (for bug fixes / features) (if applicable)
- [x] Contains **NO** breaking changes

## Other information
Correcting the duplicate name check surfaced an issue in the update category command. The update operation was throwing the following exception under all conditions:

{"Missing type map configuration or unsupported mapping.\r\n\r\nMapping types:\r\nCategoryViewModel -> Category\r\nMoneyFox.Ui.Views.Categories.ModifyCategory.CategoryViewModel -> MoneyFox.Core.ApplicationCore.Domain.Aggregates.CategoryAggregate.Category"}{"Missing type map configuration or unsupported mapping.\r\n\r\nMapping types:\r\nCategoryViewModel -> Category\r\nMoneyFox.Ui.Views.Categories.ModifyCategory.CategoryViewModel -> MoneyFox.Core.ApplicationCore.Domain.Aggregates.CategoryAggregate.Category"}

This issue has been resolved, too. Update operations now function properly.

### CODE REVIEW

**Comment by kg8z** [comment]
@NPadrutt - Fixing the duplicate name check logic surfaced an issue with the update category command logic. It looks like changes to the domain and "Features" code broke category updates. A fix for this issue is in the PR, too. I modeled my approach in Class MoneyFox.Core.Features._Legacy_.Categories.UpdateCategory.UpdateCategory after the pattern you used for payments since that was done recently. Let me know if you prefer a different approach.

Also, saving changes to Account objects is throwing the same type of exception for the same reason. Would you like me to create a new issue or submit a fix as part of this PR?

**Comment by NPadrutt** [comment]
hey @kg8z 
Thanks for the PR and spotting the issues. If you could create a new PR for accounts with the same adjustment that would be great. Getting rid of Automapper would be pretty cool. At least for the moment it seems to cause more issues than it solves.

**Comment by kg8z** [comment]
@NPadrutt - You got it. I'll submit a new Issue for the problem editing accounts.

**Comment by kg8z** [comment]
@NPadrutt  - The account update fixes have been added to the PR. Everything should be good-to-go.

**Comment by NPadrutt** [comment]
Thank you @kg8z

**Pull request merged**
