### PR TITLE
Bugfix issue2064

### PR DESCRIPTION
**Pull request by kg8z**
Issue: #2064 

## PR Type
What kind of change does this PR introduce?

Bugfix
Feature

Refactoring (no functional changes, no api changes)

## What is the current behavior?

Error messages in dialog screens (Account and Category management) were not being displayed and causing the "Loading..." dialog to be displayed indefinitely (app hang).

User was prohibited from reusing account names at all, whether the conflict was with an active or deleted account.

## What is the new behavior?
Error messages in open dialog pages (Account and Category management) are now displayed properly.

When duplicate account names are found for active accounts, the user is given the option to proceed with allowing the duplicate (both adding accounts and renaming existing accounts). Reuse of an account name for a deleted account does not present a warning and the account is created.

Moved a few routines from AddAccountViewModel and EditAccountViewModel to the base class ModifyAccountViewModel to allow use of common code for add and update operations.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] Tested code on Windows
- [x] Tested code on Android
- [ ] Tested code on iOS
- [ ] Tests for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Contains **NO** breaking changes

Unable to test on iOS for this PR.

## Other information

I modified the value of the Strings resource named DuplicateAccountMessage from "An account with that name already exists." to "An account with that name already exists. **Continue with saving?**" This coincides with the new functionality allowing the user to have multiple accounts with the same name. I used Google Translate to update all of the localization resource files to include the additional "Continue with saving?"

### CODE REVIEW

**Comment by NPadrutt** [comment]
@kg8z thanks for your PR!
I see what you mean that it's not so nice to close and open the content dialog when there is a name clash. ^^ 
For the moment I think it's fine and a step up from what we had so far. To get a step further I thinking about changing the creation into a side panel similar to how for example todo solves that: 
image

**Comment by kg8z** [comment]
@NPadrutt  - I think the side panel idea is a great one. Much more modern and intuitive than a dialog anyway. I was also giving some thought to data validation last night. It occurred to me that some form of standardized validation in the Model classes that compartmentalizes the logic and allows the ViewModel to make a simple call (e.g. MyClass.Validate()) then take appropriate action based on the result could be more streamlined. I was bouncing ideas around using Behaviors, IValidatableObject, and IValidationRule last night. The IValidatableObject and IValidationRule don't really seem to add much value beyond defining interfaces for you; all of the work to implement the validation logic, call it, and take action is still the developer's responsibility so not really sure why you'd both using these interfaces at all. Regardless, what are your thoughts on this approach? I figured if we had standard interfaces/classes for validation is could simplify and streamline presentation in the View.

**Comment by NPadrutt** [comment]
I think moving the validation to the model itself makes a lot of sense to me. In the Entities we actually do that this way too, so would also make sense to have that in the ViewModels.
I actually don't know the IValidatableObject and IValidationRule. But there is also the ObservableValidator in the Community Toolkit: https://docs.microsoft.com/en-us/windows/communitytoolkit/mvvm/observablevalidator
Maybe this could be hooked up in a nice way. 
But yeah, I really like the thought. How about you create an issue for streamlining the validation and we can see what works best?

**Comment by kg8z** [comment]
Will do! I saw the INotifyDataErrorInfo interface as I was thinking about it but didn't notice the underlying ObservableValidator base class. Very cool. I'll submit an issue and we can try explore the different approaches.

**Pull request merged**
