### PR TITLE
Issue 1560 - partially done

### PR DESCRIPTION
**Pull request by FilipHarcula**
Issue: #
https://github.com/MoneyFox/MoneyFox/issues/1560

## PR Type
What kind of change does this PR introduce?

Feature

## What is the current behavior?

No information is showed in backup view about logged user.

## What is the new behavior?
In mobile apps showing user's name and email centered under backup view header and title. In UWP app there is profile photo icon, user's name and email centered under view header. See attached images. I had problem with getting a profile photo of user. After research I found there might be some problems with it. Docs for Microsoft graph API shows example, that is working only for work or school accounts. So that's why I called it "partially done", there is problem with user profile photo but I kept default "no-photo" on UWP app.
android
uwp

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ✓ ] Tested code on Windows
- [ ✓ ] Tested code on Android
- [ x ] Tested code on iOS
- [ x ] Tests for the changes have been added (for bug fixes / features) (if applicable)
- [ ✓ ] Contains **NO** breaking changes

Had some laptop problems with testing on iOS.

### CODE REVIEW

**Comment by NPadrutt** [comment]
Sorry my late response.
That looks very cool. Is there a reason why you introduced the profile image in the UWP version only? 
Also is it possible to load the profile image for the work and school accounts and have the default one for private accounts until we have a solution for that?

**Comment by FilipHarcula** [comment]
> Sorry my late response!
> That looks very cool. Is there a reason why you introduced the profile image in the UWP version only?
> Also is it possible to load the profile image for the work and school accounts and have the default one for private accounts until we have a solution for that?



> Sorry my late response!
> That looks very cool. Is there a reason why you introduced the profile image in the UWP version only?
> Also is it possible to load the profile image for the work and school accounts and have the default one for private accounts until we have a solution for that?

Hi, no problem.
In the UWP I used the PersonPicture tag, which automatically adds this profile image. But this tag is not working in mobile views. To show image like that in mobile views I would have to download some. But I was thinking maybe you will want to create one or use the app logo there, to have same default images in UWP and mobile apps. So I left it like it is.
Solution like I left it always returns null in user.Photo. Maybe I miss something, don't know. I tried to work with Stream there but it didn't help. Really don't know. Here I found something about how to get photo from work or school accounts. https://docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-1.0 Again, maybe I was doing something wrong but working with that GET request didn't help me too. Docs are from 10/27/2020, so maybe we have to wait a bit with it. Maybe my knowledge is poor. No idea about that.
So yes, we can have the default picture for all apps, but right now I don't know if it is possible to have any real profile photo there.

**Comment by NPadrutt** [comment]
I see I see.
When I have a bit of time I'll have a look at the profile picture. Maybe I can find something. 
Do you want to keep this PR open till then or shall we progress to review / merging?

**Comment by FilipHarcula** [comment]
> I see I see.
> When I have a bit of time I'll have a look at the profile picture. Maybe I can find something.
> Do you want to keep this PR open till then or shall we progress to review / merging?

Sorry

**Comment by FilipHarcula** [comment]
> I see I see.
> When I have a bit of time I'll have a look at the profile picture. Maybe I can find something.
> Do you want to keep this PR open till then or shall we progress to review / merging?

Sorry for late response. 
I think we can progress to review.

**Comment by NPadrutt** [comment]
@FilipHarcula Did you close the PR on purpose or was that an accident? Since when you close it I can't review it ;)

**Comment by FilipHarcula** [comment]
> @FilipHarcula Did you close the PR on purpose or was that an accident? Since when you close it I can't review it ;)

Till now I had no idea I did it. Sorry.

**Comment by NPadrutt** [comment]
then just let's reopen it

**Comment by NPadrutt** [comment]
So first thing would be the unit tests. It seems there are currently a couple which fail.

**Comment by FilipHarcula** [comment]
> So first thing would be the unit tests. It seems there are currently a couple which fail.

It should be okay right now.

**Comment by NPadrutt** [comment]
thanks very much @FilipHarcula  :)

**Comment by FilipHarcula** [comment]
> thanks very much @FilipHarcula :)

No problem :) Thank you for approach :)

**Pull request merged**
